/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package the.wheel.deal;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author OMEN
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
//        ResizePhoto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        uName = new javax.swing.JTextField();
        Password_ = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        labelReg = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        AdminLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0, 90));

        jLabel2.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Login");

        jLabel3.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Harrington", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        uName.setBackground(new java.awt.Color(0, 0, 0));
        uName.setFont(new java.awt.Font("Harrington", 0, 14)); // NOI18N
        uName.setForeground(new java.awt.Color(255, 255, 255));
        uName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uNameActionPerformed(evt);
            }
        });

        Password_.setBackground(new java.awt.Color(0, 0, 0));
        Password_.setFont(new java.awt.Font("Harrington", 0, 14)); // NOI18N
        Password_.setForeground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Harrington", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dont have an account??");

        labelReg.setBackground(new java.awt.Color(255, 255, 255));
        labelReg.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        labelReg.setForeground(new java.awt.Color(255, 255, 255));
        labelReg.setText("Register!!");
        labelReg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelRegMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelRegMouseExited(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the/wheel/deal/blogin.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel6MouseExited(evt);
            }
        });

        AdminLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AdminLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the/wheel/deal/admin.png"))); // NOI18N
        AdminLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AdminLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117)
                        .addComponent(AdminLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(109, 109, 109)
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(labelReg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Password_, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(35, 35, 35)
                            .addComponent(jLabel6))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(AdminLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Password_, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(labelReg))
                .addGap(101, 101, 101))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 530, 480));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\OMEN\\Desktop\\car hire resources\\peter-broomfield-m3m-lnR90uM-unsplash (1).jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 600));

        setSize(new java.awt.Dimension(1086, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void uNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uNameActionPerformed

    private void labelRegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegMouseClicked
        // TODO add your handling code here:
        Register reg=new Register();
        reg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_labelRegMouseClicked
    
//     private ImageIcon ResizePhoto(String ImagePath,byte[]pic)
//    {
//        ImageIcon MyImage=null;
//        if(ImagePath!=null){
//            MyImage=new ImageIcon(ImagePath);
//          }
//        else{
//            MyImage=new ImageIcon(pic);
//        
//        }
//        Image img=MyImage.getImage();
//        Image newImg=img.getScaledInstance(AdminLbl.getWidth(), AdminLbl.getHeight(), Image.SCALE_SMOOTH);
//        ImageIcon image=new ImageIcon(newImg);
//        return image;
//    
//    }
    
    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
//         if(RoleCb.getSelectedIndex()==-1)
//        {
//            JOptionPane.showMessageDialog(this," Client or Admin?");
//        
//        }
//        else if(RoleCb.getSelectedIndex()==0)
//        {
//            if (uName.getText().isEmpty()|| Password_.getText().isEmpty())
//            {
//                JOptionPane.showMessageDialog(this, "Enter Username and Password");
//            }
//            else if(uName.getText().equals("Admin")&&Password_.getText().equals("Password"))
//            {
//               new Admin_Menu().setVisible(true);
//                this.dispose();
//            }
//            else
//            {
//                 JOptionPane.showMessageDialog(this,"Wrong Admin Name or Password!!!");
//                 uName.setText("");
//                 Password_.setText("");
//            }
//        }else{
        
         try {
           
            Connection conn;
            ResultSet rs;
            ResultSet rs2;
            Statement stmt;

            conn = (Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/thewheeldeal", "root", "");
            stmt = conn.createStatement();

            String username = uName.getText();
           
            String Pass = Password_.getText();
          
            String sqlChecker="SELECT * from users WHERE Password = '"+ Pass +"' AND Username = '"+username+"'";
            rs=stmt.executeQuery(sqlChecker);
            
//            String sql2 ="SELECT * from staff WHERE Password = '"+ Pass +"' AND Username = '"+username+"'";
//            rs2 = stmt.executeQuery(sql2);
            if(rs.next()){
                 this.setVisible(false);
                User_Interface a = new User_Interface();
                a.setVisible(true);
                
             
             
            }
//            else if(rs2.next()){
//                this.setVisible(false);
//                StaffMenu a = new StaffMenu();
//                a.setVisible(true);
//                
//               
//             
//            }
            else if(uName.getText().equals("Admin")&&Password_.getText().equals("Password") ){
                this.setVisible(false);
                Admin_Menu a  = new Admin_Menu();
                a.setVisible(true);
            } else{
                
                 JOptionPane.showMessageDialog(Login.this, "Wrong credentials");
            } 
                 
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, e);
        }
    
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseEntered
        // TODO add your handling code here:
         jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the/wheel/deal/rlogin.png"))); 
    }//GEN-LAST:event_jLabel6MouseEntered

    private void jLabel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseExited
        // TODO add your handling code here:
         jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the/wheel/deal/blogin.png"))); 
    }//GEN-LAST:event_jLabel6MouseExited

    private void labelRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegMouseEntered
        // TODO add your handling code here:
       
        labelReg.setForeground(new java.awt.Color(255, 51, 51));
    }//GEN-LAST:event_labelRegMouseEntered

    private void labelRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelRegMouseExited
        // TODO add your handling code here:
        labelReg.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_labelRegMouseExited

    private void AdminLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AdminLblMouseClicked
        // TODO add your handling code here:
         StaffLogin slg = new StaffLogin();
        slg.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AdminLbl;
    private javax.swing.JPasswordField Password_;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelReg;
    private javax.swing.JTextField uName;
    // End of variables declaration//GEN-END:variables
}
