/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package the.wheel.deal;

import java.sql.*;
import java.awt.*;
import java.util.*;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nelso
 */
public class User_Interface extends javax.swing.JFrame {

    /**
     * Creates new form User_Interface
     */
    public User_Interface() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchbar = new javax.swing.JTextField();
        serach_bn = new javax.swing.JLabel();
        Category_combobox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        brand_label = new javax.swing.JLabel();
        Brands_Combobox = new javax.swing.JComboBox<>();
        loadbn = new javax.swing.JLabel();
        searchbn = new javax.swing.JLabel();
        viewbn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        logo_label = new javax.swing.JLabel();
        menu_icon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableData = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        car_preview = new javax.swing.JLabel();
        car_name = new javax.swing.JLabel();
        cypi = new javax.swing.JLabel();
        rent_bn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        numplate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        searchbar.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N

        serach_bn.setBackground(new java.awt.Color(255, 255, 255));
        serach_bn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/search.png"))); // NOI18N
        serach_bn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serach_bnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serach_bnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serach_bnMouseExited(evt);
            }
        });

        Category_combobox.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        Category_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Saloon", "Truck", "Station Wagon", "Trailer", "Sports Car", "SUV", "Van" }));
        Category_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Category_comboboxActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/ctg.png"))); // NOI18N

        brand_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brand_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/brand.png"))); // NOI18N

        Brands_Combobox.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        Brands_Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Mercedes", "Honda", "Toyota", "Nissan", "Volkswagen", "Mitsubishi", "Porsche", "Chevrolet", "BMW", "Ford", "Audi", "Jeep", "Subaru", "Mazda", "Mini" }));
        Brands_Combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Brands_ComboboxActionPerformed(evt);
            }
        });

        loadbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/ld1.png"))); // NOI18N
        loadbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadbnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loadbnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loadbnMouseExited(evt);
            }
        });

        searchbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the/wheel/deal/search.png"))); // NOI18N
        searchbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchbnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchbnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchbnMouseExited(evt);
            }
        });

        viewbn.setText("View Available Cars");
        viewbn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchbn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serach_bn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(viewbn, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(loadbn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(brand_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Brands_Combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Category_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Category_combobox, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Brands_Combobox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addComponent(brand_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(loadbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(serach_bn)
                            .addComponent(searchbar)
                            .addComponent(searchbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(viewbn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        logo_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the/wheel/deal/l0g0.png"))); // NOI18N

        menu_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menu_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/menu2.png"))); // NOI18N

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the/wheel/deal/menu2.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        username1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username1.setText("User");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(menu_icon)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logo_label, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(menu_icon)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(username1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        TableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Category", "Price", "Number Plate"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableData);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/av.png"))); // NOI18N

        car_preview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        car_preview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/the/wheel/deal/lali-ho.png"))); // NOI18N
        car_preview.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        car_name.setBackground(new java.awt.Color(255, 255, 255));
        car_name.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        car_name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cypi.setBackground(new java.awt.Color(255, 255, 255));
        cypi.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        cypi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        rent_bn.setText("Rent car");
        rent_bn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rent_bnMouseClicked(evt);
            }
        });

        jButton2.setText("View details");

        numplate.setBackground(new java.awt.Color(255, 255, 255));
        numplate.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        numplate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel3.setText("Car Name : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel5.setText("Daily Price : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel6.setText("Number Plate :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(car_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cypi, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(29, 29, 29)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(car_name, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numplate, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(rent_bn, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(rent_bn)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numplate, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(car_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cypi, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(car_preview, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TableDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataMouseClicked

        //displaying vehicleimage information on the field belowS
        DefaultTableModel model = (DefaultTableModel) TableData.getModel();
        int MyIndex = TableData.getSelectedRow();
        String car_namme = (model.getValueAt(MyIndex, 0).toString());
        String car_pricee = (model.getValueAt(MyIndex, 2).toString());
        String num_plate = (model.getValueAt(MyIndex, 3).toString());
        car_name.setText(car_namme);
        cypi.setText(car_pricee);
        numplate.setText(num_plate);

        FetchPhoto(car_namme);
    }//GEN-LAST:event_TableDataMouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void loadbnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadbnMouseExited
        // TODO add your handling code here:
        loadbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/ld1.png")));
    }//GEN-LAST:event_loadbnMouseExited

    private void loadbnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadbnMouseEntered
        // TODO add your handling code here:
        loadbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/ld2.png")));
    }//GEN-LAST:event_loadbnMouseEntered

    private void loadbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadbnMouseClicked
        // emptying the table
        DefaultTableModel model = (DefaultTableModel) TableData.getModel();
        model.setRowCount(0);

        try {
            Connection conn;
            ResultSet rs;
            ResultSet rs2;
            Statement stmt;

            //connected to the database
            conn = (Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/fleet", "root", "");
            stmt = conn.createStatement();

            //retreiving ALL data from the database
            String sql2 = "SELECT vehicles.vehicle_name, vehicles.number_plate, brand.Brand_Name , vehicle_type.type_name ,vehicles.vehicle_image, vehicles.price  FROM `vehicles` INNER JOIN brand ON vehicles.vehicle_brand_id = brand.Brand_ID INNER JOIN vehicle_type ON vehicles.vehicle_type_id = vehicle_type.type_id WHERE 1";
            rs = stmt.executeQuery(sql2);
  
               
//           //getting user profile photo;
//            String sql1 = "SELECT * FROM users WHERE username ='" + namme + "'";
//            rs2 = stmt.executeQuery(sql1);
//            while(rs2.next()){
//                
//                
//            }
            

            //looping to load data into the table until theres no more data to display
            while (rs.next()) {

                //vehicle name data
                String vehicle_name = rs.getString("vehicle_name");

                //vehicle category data
                String car_brand = rs.getString("Brand_Name");
                String car_type = rs.getString("type_name");
                String car_ctg = car_brand + " " + car_type;

                //vehicle_price data
                //had to convert to string cause this work sucks
                int car_price = rs.getInt("price");
                String c_price = "Ksh. " + Integer.toString(car_price);

                //vehicle number plate
                String num_plate = rs.getString("number_plate");

                //vehicle image dara
                //                byte [] car_img=rs.getBytes("vehicle_image");
                //                ImageIcon img = new ImageIcon(car_img);
                //filling the retreived data in an array in order to display them in a row
                String vehicles_available[] = {vehicle_name, car_ctg, c_price, num_plate};

                DefaultTableModel tb = (DefaultTableModel) TableData.getModel();
                tb.addRow(vehicles_available);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_loadbnMouseClicked

    private void Brands_ComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Brands_ComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Brands_ComboboxActionPerformed

    private void Category_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Category_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Category_comboboxActionPerformed

    private void serach_bnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serach_bnMouseExited
        // TODO add your handling code here:
        serach_bn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/search.png")));
    }//GEN-LAST:event_serach_bnMouseExited

    private void serach_bnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serach_bnMouseEntered
        // TODO add your handling code here:
        serach_bn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/load.png")));
    }//GEN-LAST:event_serach_bnMouseEntered

    private void serach_bnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serach_bnMouseClicked

        // parsing the user input into a string
        String search_item = searchbar.getText();

        if (search_item.trim().isBlank()) {
            JOptionPane.showMessageDialog(User_Interface.this, "There's nothing in the search bar !!!");
        } else {

            try {
                Connection conn;
                ResultSet rs;
                Statement stmt;

                //connecting to the database
                conn = (Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/fleet", "root", "");
                stmt = conn.createStatement();

                //clearing the table to refill it
                DefaultTableModel model = (DefaultTableModel) TableData.getModel();
                model.setRowCount(0);

                //SQl string for the search operation
                String searchin = "SELECT vehicles.vehicle_name, vehicles.number_plate, brand.Brand_Name , vehicle_type.type_name ,vehicles.vehicle_image, vehicles.price  FROM `vehicles` INNER JOIN brand ON vehicles.vehicle_brand_id = brand.Brand_ID INNER JOIN vehicle_type ON vehicles.vehicle_type_id = vehicle_type.type_id WHERE brand.Brand_Name = '" + search_item + "'OR vehicle_type.type_name = '" + search_item + "' OR vehicles.vehicle_name LIKE '%" + search_item + "%';  ";
                rs = stmt.executeQuery(searchin);

                //retreiving the data from the database
                while (rs.next()) {
                    //vehicle name data
                    String vehicle_name = rs.getString("vehicle_name");

                    //vehicle category data
                    String car_brand = rs.getString("Brand_Name");
                    String car_type = rs.getString("type_name");
                    String car_ctg = car_brand + " " + car_type;

                    //vehicle_price data
                    //had to convert to string cause this work sucks
                    int car_price = rs.getInt("price");
                    String c_price = "Ksh. " + Integer.toString(car_price);

                    //vehicle number plate
                    String num_plate = rs.getString("number_plate");

                    //vehicle image dara
                    //                byte [] car_img=rs.getBytes("vehicle_image");
                    //                ImageIcon img = new ImageIcon(car_img);
                    //filling the retreived data in an array in order to display them in a row
                    String vehicles_available[] = {vehicle_name, car_ctg, c_price, num_plate};

                    DefaultTableModel tb = (DefaultTableModel) TableData.getModel();
                    tb.addRow(vehicles_available);

                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }

        }
    }//GEN-LAST:event_serach_bnMouseClicked

    private void rent_bnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rent_bnMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Vehicle has been requested for hire!");
    }//GEN-LAST:event_rent_bnMouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jLabel2MouseExited

    private void searchbnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbnMouseEntered
        // TODO add your handling code here:
         searchbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/load.png")));
    }//GEN-LAST:event_searchbnMouseEntered

    private void searchbnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbnMouseExited
        // TODO add your handling code here:
        searchbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication22/search.png")));
    }//GEN-LAST:event_searchbnMouseExited

    private void searchbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchbnMouseClicked
        // TODO add your handling code here:
        String search_item = searchbar.getText();

        if (search_item.trim().isBlank()) {
            JOptionPane.showMessageDialog(User_Interface.this, "There's nothing in the search bar !!!");
        } else {

            try {
                Connection conn;
                ResultSet rs;
                Statement stmt;

                //connecting to the database
                conn = (Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/fleet", "root", "");
                stmt = conn.createStatement();

                //clearing the table to refill it
                DefaultTableModel model = (DefaultTableModel) TableData.getModel();
                model.setRowCount(0);

                //SQl string for the search operation
                String searchin = "SELECT vehicles.vehicle_name, vehicles.number_plate, brand.Brand_Name , vehicle_type.type_name ,vehicles.vehicle_image, vehicles.price  FROM `vehicles` INNER JOIN brand ON vehicles.vehicle_brand_id = brand.Brand_ID INNER JOIN vehicle_type ON vehicles.vehicle_type_id = vehicle_type.type_id WHERE brand.Brand_Name = '" + search_item + "'OR vehicle_type.type_name = '" + search_item + "' OR vehicles.vehicle_name LIKE '%" + search_item + "%';  ";
                rs = stmt.executeQuery(searchin);

                //retreiving the data from the database
                while (rs.next()) {
                    //vehicle name data
                    String vehicle_name = rs.getString("vehicle_name");

                    //vehicle category data
                    String car_brand = rs.getString("Brand_Name");
                    String car_type = rs.getString("type_name");
                    String car_ctg = car_brand + " " + car_type;

                    //vehicle_price data
                    //had to convert to string cause this work sucks
                    int car_price = rs.getInt("price");
                    String c_price = "Ksh. " + Integer.toString(car_price);

                    //vehicle number plate
                    String num_plate = rs.getString("number_plate");

                    //vehicle image dara
                    //                byte [] car_img=rs.getBytes("vehicle_image");
                    //                ImageIcon img = new ImageIcon(car_img);
                    //filling the retreived data in an array in order to display them in a row
                    String vehicles_available[] = {vehicle_name, car_ctg, c_price, num_plate};

                    DefaultTableModel tb = (DefaultTableModel) TableData.getModel();
                    tb.addRow(vehicles_available);

                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
    }//GEN-LAST:event_searchbnMouseClicked

    private void viewbnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbnMouseClicked
        // TODO add your handling code here:
           // emptying the table
        DefaultTableModel model = (DefaultTableModel) TableData.getModel();
        model.setRowCount(0);

        try {
            Connection conn;
            ResultSet rs;
            ResultSet rs2;
            Statement stmt;

            //connected to the database
            conn = (Connection) java.sql.DriverManager.getConnection("jdbc:mysql://localhost/fleet", "root", "");
            stmt = conn.createStatement();

            //retreiving ALL data from the database
            String sql2 = "SELECT vehicles.vehicle_name, vehicles.number_plate, brand.Brand_Name , vehicle_type.type_name ,vehicles.vehicle_image, vehicles.price  FROM `vehicles` INNER JOIN brand ON vehicles.vehicle_brand_id = brand.Brand_ID INNER JOIN vehicle_type ON vehicles.vehicle_type_id = vehicle_type.type_id WHERE 1";
            rs = stmt.executeQuery(sql2);
  
               
//           //getting user profile photo;
//            String sql1 = "SELECT * FROM users WHERE username ='" + namme + "'";
//            rs2 = stmt.executeQuery(sql1);
//            while(rs2.next()){
//                
//                
//            }
            

            //looping to load data into the table until theres no more data to display
            while (rs.next()) {

                //vehicle name data
                String vehicle_name = rs.getString("vehicle_name");

                //vehicle category data
                String car_brand = rs.getString("Brand_Name");
                String car_type = rs.getString("type_name");
                String car_ctg = car_brand + " " + car_type;

                //vehicle_price data
                //had to convert to string cause this work sucks
                int car_price = rs.getInt("price");
                String c_price = "Ksh. " + Integer.toString(car_price);

                //vehicle number plate
                String num_plate = rs.getString("number_plate");

                //vehicle image dara
                //                byte [] car_img=rs.getBytes("vehicle_image");
                //                ImageIcon img = new ImageIcon(car_img);
                //filling the retreived data in an array in order to display them in a row
                String vehicles_available[] = {vehicle_name, car_ctg, c_price, num_plate};

                DefaultTableModel tb = (DefaultTableModel) TableData.getModel();
                tb.addRow(vehicles_available);

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_viewbnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Brands_Combobox;
    private javax.swing.JComboBox<String> Category_combobox;
    private javax.swing.JTable TableData;
    private javax.swing.JLabel brand_label;
    private javax.swing.JLabel car_name;
    private javax.swing.JLabel car_preview;
    private javax.swing.JLabel cypi;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel loadbn;
    private javax.swing.JLabel logo_label;
    private javax.swing.JLabel menu_icon;
    private javax.swing.JLabel numplate;
    private javax.swing.JButton rent_bn;
    private javax.swing.JTextField searchbar;
    private javax.swing.JLabel searchbn;
    private javax.swing.JLabel serach_bn;
    private javax.swing.JLabel username1;
    private javax.swing.JButton viewbn;
    // End of variables declaration//GEN-END:variables

    //function to fetch the image file from the database
    private void FetchPhoto(String idd) {

        //sql query
        String Query = "SELECT vehicle_image FROM vehicles WHERE vehicle_name ='" + idd + "'";
        Statement St;
        ResultSet Rs;
        Connection Con;
        try {
            Con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fleet", "root", "");
            St = Con.createStatement();
            Rs = St.executeQuery(Query);
            if (Rs.next()) {
                //retreiving the image and displaying it
                car_preview.setIcon(ResizePhoto(null, Rs.getBytes("vehicle_image")));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        } //To change body of generated methods, choose Tools | Templates.
    }

    //function that resizes the image to  fit the label
    private Icon ResizePhoto(String ImagePath, byte[] pic) {

        ImageIcon MyImage = null;
        if (ImagePath != null) {
            MyImage = new ImageIcon(ImagePath);
        } else {
            MyImage = new ImageIcon(pic);

        }
        Image img = MyImage.getImage();
        Image newImg = img.getScaledInstance(car_preview.getWidth(), car_preview.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon image = new ImageIcon(newImg);
        return image; //To change body of generated methods, choose Tools | Templates.
    }
}
